Repository 202306-NEA-DZ-FEW/student-store-team-2, pull requests merged in 2023-10, with the labels that each got.

#6 1 create the project structure
  .github/workflows/issue-autolink.yml
  .prettierignore
  package-lock.json
  package.json
  src/app/favicon.ico
  src/app/globals.css
  src/app/layout.js
  src/app/page.js
  src/app/products/[productId].jsx
  src/app/products/page.jsx
  src/components/footer/Footer.jsx
  src/components/footer/test/Footer.test.js
  src/components/footer/test/__snapshots__/Footer.test.js.snap
  src/components/navbar/Navbar.jsx
  src/components/navbar/test/Navbar.test.js
  src/components/navbar/test/__snapshots__/Navbar.test.js.snap
  src/layout/Layout.jsx
  src/pages/404.jsx
  src/pages/_app.jsx
  src/pages/_document.jsx
  src/pages/api/hello.js
  src/pages/index.jsx
  src/styles/globals.css
Labels: enhancement, structure

#11 fix(github workflow): fix the issue-autolink
  .github/workflows/issue-autolink.yml
Labels: bug, structure

#12 2 tailwind css configuration
  .prettierignore
  package-lock.json
  package.json
  postcss.config.js
  src/app/globals.css
  src/components/navbar/Navbar.jsx
  tailwind.config.js
Labels: design

#27 feat(firebase): add firebase, firestore, auth, firestorage
  package-lock.json
  package.json
  src/lib/firebase.js
Labels: enhancement, Firebase

#29 feat(navbar): create a navbar
  package-lock.json
  package.json
  src/app/globals.css
  src/app/layout.js
  src/app/page.js
  src/components/mobileSidebar/MobileSidebar.jsx
  src/components/navbar/Navbar.jsx
  src/components/portal/Portal.jsx
  src/components/search/Searchbar.jsx
  tailwind.config.js
Labels: enhancement

#30 feat(productcard): add itemLabel for productCard
  package-lock.json
  package.json
  src/app/globals.css
  src/app/layout.js
  src/components/productCard/itemLabel/ItemLabel.jsx
  src/components/productCard/itemLabel/__test__/ItemLabel.test.js
  tailwind.config.js
Labels: enhancement, design

#38 feat(home page): add testimonials
  src/app/page.js
  src/components/productCard/itemConditionLabel/__test__/__snapshots__/ItemConditionLabel.test.js.snap
  src/components/productCard/itemLabel/__test__/__snapshots__/ItemLabel.test.js.snap
  src/components/starRating/StarRating.js
  src/components/testimonials/Testimonials.jsx
  src/components/testimonials/test/Testimonials.test.js
  src/components/testimonials/test/__snapshots__/Testimonials.test.js.snap
Labels: enhancement

#28 23 product card
  .prettierignore
  next.config.js
  package-lock.json
  package.json
  src/app/globals.css
  src/components/footer/__test__/Footer.test.js
  src/components/footer/__test__/__snapshots__/Footer.test.js.snap
  src/components/navbar/__test__/Navbar.test.js
  src/components/navbar/__test__/__snapshots__/Navbar.test.js.snap
  src/components/navbar/test/__snapshots__/Navbar.test.js.snap
  src/components/productCard/ProductCard.jsx
  src/components/productCard/__test__/__snapshots__/productCard.test.js.snap
  src/components/productCard/__test__/productCard.test.js
  src/components/productCard/itemLabel/ItemLabel.jsx
  src/components/productCard/itemLabel/__test__/__snapshots__/ItemLabel.test.js.snap
Labels: enhancement, design

#34 feat(footer.jsx): create the footer component
  public/img/dhl.png
  public/img/pngwing.com (4).png:Zone.Identifier
  public/img/pngwing.com (5).png:Zone.Identifier
  public/img/yalidine.png
  public/img/yalidine.png:Zone.Identifier
  src/app/globals.css
  src/app/page.js
  src/components/footer/Footer.jsx
  src/components/footer/__test__/__snapshots__/Footer.test.js.snap
Labels: enhancement, design

#50 feat(component): add hero carousel
  package-lock.json
  src/app/[locale]/carousel.css
  src/app/[locale]/layout.js
  src/app/[locale]/page.js
  src/components/heroCarousel/HeroCarousel.jsx
  src/components/heroCarousel/__test__/HeroCarousel.test.js
  src/components/heroCarousel/__test__/__snapshots__/HeroCarousel.test.js.snap
  src/components/navbar/Navbar.jsx
  src/components/navbar/__test__/__snapshots__/Navbar.test.js.snap
  yarn.lock
Labels: enhancement, design

#54 chore: added app routing files
  package-lock.json
  src/app/[locale]/(auth)/profile/page.js
  src/app/[locale]/(auth)/sign-in/page.js
  src/app/[locale]/(auth)/sign-up/page.js
  src/app/[locale]/about/page.js
  src/app/[locale]/dashboard/page.js
  src/components/productCard/ProductCard.jsx
  src/components/productCard/itemConditionLabel/ItemConditionLabel.jsx
  src/components/productCard/itemLabel/ItemLabel.jsx
  yarn.lock
Labels: structure

#63 46 edit profile page
  messages/ar.json
  messages/en.json
  next.config.js
  package-lock.json
  package.json
  src/app/[locale]/(auth)/profile/page.js
  src/app/[locale]/(auth)/sign-in/page.js
  src/app/[locale]/(auth)/sign-up/page.js
  src/components/authPage/authFooter/AuthFooter.js
  src/components/authPage/authFooter/__test__/AuthFooter.test.js
  src/components/authPage/authFooter/__test__/__snapshots__/AuthFooter.test.js.snap
  src/components/authPage/authHeader/AuthHeader.js
  src/components/authPage/authHeader/__test__/AuthHeader.test.js
  src/components/authPage/authHeader/__test__/__snapshots__/AuthHeader.test.js.snap
  src/components/form/Form.js
  src/components/form/__test__/Form.test.js
  src/components/form/__test__/Forrm.test.js
  src/components/form/__test__/__snapshots__/Form.test.js.snap
  src/components/imageFolder/UploadImage.js
  src/components/imageFolder/__test__/UploadImage.test.js
  src/components/imageFolder/__test__/__snapshots__/UploadImage.test.js.snap
  src/components/productCard/itemLabel/ItemLabel.jsx
  src/components/productCard/itemLabel/__test__/__snapshots__/ItemLabel.test.js.snap
  src/components/securityForm/SecurityForm.js
  src/components/userProfileForm/UserProfileForm.js
  src/components/userProfileForm/__test__/UserProfileForm.test.js
  src/components/userProfileForm/__test__/__snapshots__/UserProfileForm.test.js.snap
  src/components/userProvider/UserProvider.js
  src/lib/authDetails.js
  src/lib/firestore.js
  yarn.lock
Labels: enhancement
