Repository 202306-NEA-DZ-FEW/student-store-team-2, pull requests merged in 2023-11, with the labels that each got.

#66 feat(authentication): handle the session in the client side
  src/app/[locale]/(auth)/profile/page.js
  src/app/[locale]/(auth)/sign-in/page.js
  src/app/[locale]/layout.js
  src/app/api/auth/route.js
  src/app/api/userData/route.js
  src/components/form/Form.js
  src/components/form/__test__/Form.test.js
  src/components/imageFolder/__test__/UploadImage.test.js
  src/components/mobileSidebar/test/MobileSidebar.test.js
  src/components/navbar/__test__/Navbar.test.js
  src/components/userProfileForm/UserProfileForm.js
  src/components/userProfileForm/__test__/UserProfileForm.test.js
  src/components/userProvider/UserProvider.js
  src/components/userProvider/__test__/UserProvider.test.js
  src/components/userStatus/UserStatus.js
  src/components/userStatus/__test__/UserStatus.test.js
  src/lib/authDetails.js
  src/lib/firestore.js
Labels: bug, enhancement, deployment

#71 fix(product card): fix the hydration error
  src/app/[locale]/layout.js
  src/app/[locale]/loader.css
  src/app/[locale]/page.js
  src/components/addedGrid/AddedGrid.jsx
  src/components/addedGrid/__test__/__snapshots__/AddedGrid.test.js.snap
  src/components/productCard/ProductCard.jsx
  src/components/productCard/__test__/__snapshots__/productCard.test.js.snap
  src/components/productCard/itemLabel/ItemLabel.jsx
  src/components/userProvider/UserProvider.js
Labels: bug

#75 72 product listing page
  messages/ar.json
  messages/en.json
  next.config.js
  package-lock.json
  package.json
  products.js
  public/img/dhl.png
  public/img/yalidine.png
  src/app/[locale]/dashboard/page.js
  src/components/addProduct/AddProductForm.jsx
  src/components/addProduct/__test__/AddProductForm.test.js
  src/components/addProduct/__test__/__snapshots__/AddProductForm.test.js.snap
  src/components/dashboardNavLinks/NavLinks.jsx
  src/components/dashboardNavLinks/__test__/NavLinks.test.js
  src/components/dashboardNavLinks/__test__/__snapshots__/NavLinks.test.js.snap
  src/components/myListings/MyListings.jsx
  src/components/myListings/__tests__/MyListings.test.js
  src/components/myListings/__tests__/__snapshots__/MyListings.test.js.snap
  src/lib/_cloudinary.js
  yarn.lock
Labels: enhancement, design

#74 52 product display
  package-lock.json
  package.json
  public/img/product1.jpg
  public/img/product2.jpg
  public/img/product3.jpg
  public/img/product4.jpg
  src/app/[locale]/products/[id]/page.jsx
  src/app/[locale]/products/[productId].jsx
  src/components/contactDetails/ContactDetails/ContactDetails.jsx
  src/components/contactDetails/__test__/ContactDetails.test.js
  src/components/contactDetails/__test__/__snapshots__/ContactDetails.test.js.snap
  src/components/product-display/ProductDisplay.jsx
  src/components/product-display/__test__/ProductDisplay.test.js
  src/components/product-display/__test__/__snapshots__/ProductDisplay.test.js.snap
  src/components/productDetailsSection/ProductDetailSection.jsx
  src/components/productDetailsSection/__test__/ProductDetailSection.test.js
  src/components/productDetailsSection/__test__/__snapshots__/ProductDetailSection.test.js.snap
  src/components/profilePicture/ProfilePic.jsx
  src/components/profilePicture/__test__/__snapshots__/profilePic.test.js.snap
  src/components/profilePicture/__test__/profilePic.test.js
  src/components/profileUserInformation/ProfileUserInfo.jsx
  src/components/profileUserInformation/__test__/ProfileUserInfo.test.js
  src/components/profileUserInformation/__test__/__snapshots__/ProfileUserInfo.test.js.snap
  tailwind.config.js
Labels: enhancement

#79 feat(products listing): add the index when adding a product
  src/components/addProduct/AddProductForm.jsx
  src/lib/firestore.js
Labels: enhancement, deployment

#102 feat(product listing): add image compression
  .env
  package-lock.json
  package.json
  src/components/addProduct/AddProductForm.jsx
  src/lib/_cloudinary.js
Labels: enhancement

#103 fix(product listing): fix the name of the fields
  src/components/addProduct/AddProductForm.jsx
  src/components/addProduct/__test__/__snapshots__/AddProductForm.test.js.snap
Labels: bug

#113 110 dashboard migrate the to supabase
  messages/en.json
  package-lock.json
  package.json
  src/app/[locale]/dashboard/page.js
  src/app/[locale]/layout.js
  src/components/addProduct/AddProductForm.jsx
  src/components/addProduct/__test__/AddProductForm.test.js
  src/components/addProduct/__test__/__snapshots__/AddProductForm.test.js.snap
  src/components/dashboardDisplay/DashboardDisplay.jsx
  src/components/dashboardDisplay/__test__/DashboardDisplay.test.js
  src/components/dashboardNavLinks/NavLinks.jsx
  src/components/form/__test__/Form.test.js
  src/components/googleLoginButton/__test__/GoogleButton.test.js
  src/components/imageFolder/__test__/UploadImage.test.js
  src/components/mobileSidebar/test/MobileSidebar.test.js
  src/components/navbar/__test__/Navbar.test.js
  src/components/productItems/ProductItem.jsx
  src/components/productItems/__test__/ProductItem.test.js
  src/components/productItems/__test__/__snapshots__/ProductItem.test.js.snap
  src/components/sortingControl/__test__/__snapshots__/SortingControl.test.js.snap
  src/components/uploadId/__test__/UploadId.test.js
  src/components/userProfileForm/UserProfileForm.js
  src/components/userProfileForm/__test__/UserProfileForm.test.js
  src/components/userProvider/UserProvider.js
  src/components/userProvider/__test__/UserProvider.test.js
  src/components/userStatus/__test__/UserStatus.test.js
  src/lib/_cloudinary.js
  src/lib/authDetails.js
  src/lib/firestore.js
  src/lib/supabase.js
Labels: enhancement

#125 feat(users data): migrate the users data to supabase
  src/app/[locale]/dashboard/page.js
  src/components/dashboardDisplay/DashboardDisplay.jsx
  src/components/dashboardDisplay/__test__/__snapshots__/DashboardDisplay.test.js.snap
  src/components/userProvider/UserProvider.js
  src/lib/authDetails.js
Labels: enhancement, supabase

#172 163 map implementation UI 1
  next.config.js
  src/app/[locale]/products/[id]/page.js
  src/components/map/Map.js
  src/components/tabs/TabsComponent.jsx
  src/components/tabs/locationTab/LocationTab.jsx
  src/components/tabs/locationTab/__test__/LocationTab.test.js
  src/components/tabs/locationTab/__test__/__snapshots__/LocationTab.test.js.snap
  src/lib/supabase.js
Labels: enhancement, design
